"""Changed Clubs schema and table

Revision ID: 4d1c89fb1f48
Revises: 
Create Date: 2018-08-05 21:48:17.180153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d1c89fb1f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clubs', sa.Column('date_week', sa.String(length=100), nullable=True))
    op.add_column('Clubs', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('Clubs', sa.Column('event_date', sa.String(length=100), nullable=True))
    op.add_column('Clubs', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('Clubs', sa.Column('time_end', sa.String(length=100), nullable=True))
    op.add_column('Clubs', sa.Column('time_start', sa.String(length=100), nullable=True))
    op.drop_column('Clubs', 'event_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clubs', sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('Clubs', 'time_start')
    op.drop_column('Clubs', 'time_end')
    op.drop_column('Clubs', 'location')
    op.drop_column('Clubs', 'event_date')
    op.drop_column('Clubs', 'description')
    op.drop_column('Clubs', 'date_week')
    # ### end Alembic commands ###
