"""added public id 

Revision ID: fe4b99bbfb36
Revises: 4d1c89fb1f48
Create Date: 2018-08-05 22:47:16.501880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4b99bbfb36'
down_revision = '4d1c89fb1f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clubs', sa.Column('public_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'Clubs', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Clubs', type_='unique')
    op.drop_column('Clubs', 'public_id')
    # ### end Alembic commands ###
